import { type RequestHandler } from '@sveltejs/kit';
import { db } from '$lib/server/db';
import { chats, messages } from '$lib/server/db/schema';
import { eq, and } from 'drizzle-orm';
import { getModelConfig } from '$lib/ai/providers';
import { chromium } from 'playwright';
import { renderChatToHTML } from '$lib/server/pdf/renderer';
import { GOTENBERG_URL } from '$env/static/private';

/** Extract readable text from a message, handling JSON-wrapped content */
function extractText(raw: string): string {
	if (raw.startsWith('{') && raw.endsWith('}')) {
		try {
			const parsed = JSON.parse(raw);
			if (parsed && typeof parsed === 'object' && 'text' in parsed) {
				return parsed.text || '';
			}
		} catch {
			// fallback
		}
	}
	return raw;
}

export const GET: RequestHandler = async ({ params, locals, url }) => {
	if (!locals.user) {
		return new Response('Unauthorized', { status: 401 });
	}

	const id = params.id;
	if (!id) {
		return new Response('Message ID is required', { status: 400 });
	}

	const format = url.searchParams.get('format') || 'md';

	// Join messages and chats to verify ownership
	const result = await db
		.select({ message: messages, chat: chats })
		.from(messages)
		.innerJoin(chats, eq(messages.chatId, chats.id))
		.where(and(eq(messages.id, id), eq(chats.userId, locals.user.id)))
		.limit(1);

	if (result.length === 0) {
		return new Response('Message not found or unauthorized', { status: 404 });
	}

	const msg = result[0].message;
	const chatTitle = 'Single Message Export';
	const exportDate = new Date().toLocaleDateString('en-US', {
		year: 'numeric',
		month: 'long',
		day: 'numeric',
		hour: '2-digit',
		minute: '2-digit'
	});

	// ── Markdown Export ────────────────────────────────────────────────────
	if (format === 'md') {
		let md = '';
		md += `---\n`;
		md += `type: "single_message"\n`;
		md += `exported: "${exportDate}"\n`;
		md += `platform: MicroManus\n`;
		md += `---\n\n`;

		const text = extractText(msg.content);

		if (msg.role === 'user') {
			md += `### 🧑 You\n\n`;
			md += `> ${text.split('\n').join('\n> ')}\n\n`;
		} else if (msg.role === 'assistant') {
			const modelLabel = msg.modelId
				? (getModelConfig(msg.modelId)?.label ?? msg.modelId)
				: 'Assistant';
			md += `### 🤖 ${modelLabel}\n\n`;

			if (msg.reasoning) {
				md += `<details>\n<summary>💭 Reasoning</summary>\n\n`;
				md += `${msg.reasoning}\n\n`;
				md += `</details>\n\n`;
			}

			md += `${text}\n\n`;

			if (msg.sources && Array.isArray(msg.sources) && msg.sources.length > 0) {
				md += `**📎 Sources:**\n\n`;
				(msg.sources as any[]).forEach((s: any, i: number) => {
					md += `${i + 1}. [${s.title || s.url}](${s.url})\n`;
				});
				md += `\n`;
			}
		}

		md += `\n*Generated by MicroManus · ${exportDate}*\n`;

		return new Response(md, {
			headers: {
				'Content-Type': 'text/markdown; charset=utf-8',
				'Content-Disposition': `attachment; filename="message_${id}_export.md"`
			}
		});
	}

	// ── PDF Export (Playwright Server-Side) ──────────────────────────────
	if (format === 'pdf') {
		try {
			const html = await renderChatToHTML(chatTitle, exportDate, [msg]);

			const formData = new FormData();
			formData.append(
				'files',
				new Blob([html], { type: 'text/html' }),
				'index.html' // Gotenberg requires this exact filename for the main file
			);

			// Optional: replicate your margin/footer settings
			formData.append('marginTop', '0.79'); // inches; 20mm ≈ 0.79in
			formData.append('marginBottom', '0.79');
			formData.append('marginLeft', '0');
			formData.append('marginRight', '0');
			formData.append('printBackground', 'true');
			formData.append('preferCssPageSize', 'false');

			// Footer/header must be their own HTML files if you want them
			formData.append(
				'footer',
				new Blob(
					[
						`<html><body style="width:100%;font-size:8px;color:#6b7280;padding:0 40px;display:flex;justify-content:space-between;font-family:sans-serif;">
									<span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
									<span>MicroManus</span>
								</body></html>`
					],
					{ type: 'text/html' }
				),
				'footer.html'
			);

			const res = await fetch(`${GOTENBERG_URL}/forms/chromium/convert/html`, {
				method: 'POST',
				body: formData
			});

			if (!res.ok) {
				const errText = await res.text();
				console.error('Gotenberg error:', errText);
				return new Response('Failed to generate PDF', { status: 502 });
			}

			const pdfBuffer = await res.arrayBuffer();

			return new Response(pdfBuffer, {
				headers: {
					'Content-Type': 'application/pdf',
					'Content-Disposition': `attachment; filename="message_${id}_export.pdf"`
				}
			});
		} catch (error) {
			console.error('PDF Generation Error:', error);
			return new Response('Failed to generate PDF. Make sure Playwright Chromium is installed.', {
				status: 500
			});
		}
	}

	return new Response('Unsupported format. Use ?format=pdf or ?format=md', { status: 400 });
};
